databases:
  - name: manikanta-stackoverflow-db
    plan: free
    databaseName: stackit
    user: stackit

services:
  - type: web
    name: manikanta-stackoverflow-web
    repo: https://github.com/vvmanikantasai/stackoverflow_clone.git
    branch: main
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn stackit.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: manikanta-stackoverflow-db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
